// ======= DEVICE TYPES ============================

export const CREATE_DEVICE_START = 'CREATE_DEVICE_START';
export const CREATE_DEVICE_SUCCESS = 'CREATE_DEVICE_SUCCESS';
export const CREATE_DEVICE_FAIL = 'CREATE_DEVICE_FAIL';
export const GET_DEVICES_START = 'GET_DEVICES_START';
export const GET_DEVICES_SUCCESS = 'GET_DEVICES_SUCCESS';
export const GET_DEVICES_FAIL = 'GET_DEVICES_FAIL';
export const FETCH_DEVICE_START = 'FETCH_DEVICE_START';
export const FETCH_DEVICE_SUCCESS = 'FETCH_DEVICE_SUCCESS';
export const FETCH_DEVICE_FAIL = 'FETCH_DEVICE_FAIL';
export const UPDATE_DEVICE_START = 'UPDATE_DEVICE_START';
export const UPDATE_DEVICE_SUCCESS = 'UPDATE_DEVICE_SUCCESS';
export const UPDATE_DEVICE_FAIL = 'UPDATE_DEVICE_FAIL';
export const REMOVE_DEVICE_START = 'REMOVE_DEVICE_START';
export const REMOVE_DEVICE_SUCCESS = 'REMOVE_DEVICE_SUCCESS';
export const REMOVE_DEVICE_FAIL = 'REMOVE_DEVICE_FAIL';
