export const subscriptions = [
  {
    id: 1,
    title: 'Free',
    monthly_price: 0,
    annual_price: 0,
    features: ['Up to 10 users', 'Up to 20 devices', 'No credit card required'],
    btn_label: 'Try it for free',
    highlight: false,
  },
  {
    id: 2,
    title: 'Starter',
    monthly_price: 20,
    annual_price: 192,
    features: [
      'Up to 50 users',
      'Up to 100 devices',
      'Remote control',
      'Schedule upgrade',
    ],
    btn_label: 'Subscribe',
    highlight: true,
  },
  {
    id: 3,
    title: 'Pro',
    monthly_price: 40,
    annual_price: 384,
    features: [
      'Up to 500 users',
      'Up to 1000+ devices',
      'Remote control',
      'Schedule upgrade',
      'Push notifications',
    ],
    btn_label: 'Subscribe',
    highlight: false,
  },
  {
    id: 4,
    title: 'Enterprise',
    monthly_price: 'Custom',
    annual_price: 'Custom',
    features: [
      'Unlimited users',
      'Unlimited devices',
      'Remote control',
      'Schedule upgrade',
      'Push notifications',
    ],
    btn_label: 'Subscribe',
    highlight: false,
  },
];
